name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prepare Deployment Directory
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            if [ -d '/home/BeAlert' ]; then
              cd /home/BeAlert
              git pull
            else
              cd ~
              git clone ${{ secrets.REPO_URL }} /home/BeAlert
              cd /home/BeAlert
            fi
          "

      - name: Clean and Install Dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /home/BeAlert
            rm -rf .next
            echo 'APP_VAPIDKEY=${{ secrets.APP_VAPIDKEY }}' > .env
            echo 'NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}' >> .env
            pnpm i
            pnpm build
          "

      - name: Stop Existing Services
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker stop bealert-back || true
            docker rm bealert-back || true
            pid=\$(sudo ss -lptn 'sport = :15551' | awk 'NR>1 {print \$6}' | cut -d',' -f2 | cut -d'=' -f2)
            if [ -n \"\$pid\" ]; then
              echo 'Killing process \$pid using port 15551'
              kill -9 \$pid
            fi
            if sudo ss -lptn 'sport = :15551' | grep -q :15551; then
              echo 'Failed to kill the process using port 15551' >&2
              exit 1
            fi
          "

      - name: Start Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /home/BeAlert
            chmod +x build_and_run.sh
            ./build_and_run.sh
            nohup setsid pnpm start --port 15551 > server.log 2>&1 &
          "

      - name: Verify Application is Running
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            sleep 5
            if ! sudo ss -lptn 'sport = :15551' | grep -q :15551; then
              echo 'Server did not start correctly' >&2
              cat server.log
              exit 1
            fi
          "
